import Joi from "joi";

export const registerSchema = Joi.object({
      name: Joi.string().required(),
      phoneNumber: Joi.string().required(),
      countryCode: Joi.string().required(),
      password: Joi.string().required(),
      email: Joi.string().email().optional(),
      autoGeneratedContacts: Joi.boolean().optional(),
});

export const contactSchema = Joi.object({
      name: Joi.string().required(),
      phoneNumber: Joi.string().required(),
      userID: Joi.number().required(),
});
